spring:
    groovy:
        template:
            check-template-location: false

dataSource:
    pooled: true
    jmxExport: true
    transactionAware: true
    driverClassName: org.h2.Driver
    username: sa
    password:
    dbCreate: update
    url: jdbc:h2:mem:devDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE

endpoints:
    jmx:
        unique-names: true

hibernate:
    packagesToScan: 'gormclient'